apiVersion: v1
kind: Service
metadata:
  labels:
    app: kafka
  name: kafka
  namespace: kong
spec:
  ports:
  - port: 9092
  selector:
    app: kafka
      #  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: kafka
  name: kafka
  namespace: kong
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      hostname: kafka
      containers:
      - env:
        - name: KAFKA_BROKER_ID
          value: "1"
        - name: KAFKA_CFG_ZOOKEEPER_CONNECT
          value: zookeeper-service:2181
        - name: ALLOW_PLAINTEXT_LISTENER
          value: "yes"
        image: bitnami/kafka:2.3.1
        imagePullPolicy: IfNotPresent
        name: kafka
        ports:
        - containerPort: 9092
